app:
  name: "Course APP"
  host: "0.0.0.0"
  port: 8000
  secret_key: "asdgsdggstrsr324rwqad"
  debug: true

database:
  user: 'user'
  password: 'password'
  host: 'localhost'
  port: 5433
  name: 'backend_course'